### ISSUE TITLE
Could not connect to host

### ISSUE THREAD

**Issue by user5885** [pgrimaud/horaires-ratp-sdk#2]
L'erreur intervient au moment d'appeller une fonction avec Soap.
```php
$api = new \Ratp\Api();
$version = $api->getVersion();
```

retour:
>SoapFault: Could not connect to host

**Comment by pgrimaud** [comment]
Bonjour.

As-tu complété le formulaire de demande d'accès à l'API RATP ?
https://data.ratp.fr/explore/dataset/horaires-temps-reel/

Tu vas devoir donner 1 à 3 IP(s) sur lesquelles ils vont t'ouvrir un accès.

**Comment by user5885** [comment]
C'est un peu dommage pour une API publique de devoir s'inscrire
enfin bon c'est bien la RATP...
Merci

**Comment by pgrimaud** [comment]
@user5885 Malheureusement oui. Il faut voir le côté positif. Depuis le temps qu'on attendait l'ouverture des données, c'est toujours mieux que rien. 😉
